version: '1.0'

services:

  mongodb:
      user: "root"
      build: ./mongo/.
      image: mongo:latest
      # environment:
      # - MONGO_INITDB_ROOT_USERNAME=admin
      # - MONGO_INITDB_ROOT_PASSWORD=admin

      command: mongod --port 23456
      ports:
        - 23456:23456
      networks:
        - netwdocker

  rabbitmq:
    build: backend/rabbitmq/.
    container_name: "rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - netwdocker

  fastapi:
    build: backend/fastapi/app/.
    ports:
    - 80:80
    - 8000:8000
    extra_hosts:
      - "mongodb:172.17.0.1"
    depends_on:
      - rabbitmq

    networks:
      - netwdocker

  extract:
    build: backend/extraction_worker/.
    # environment:
      # - tesseract_path=./usr/bin/tesseract
    depends_on:
      - rabbitmq
    networks:
      - netwdocker

  connectworker:
    build: backend/connectworker/.
    # environment:
    #   - MQ_HOST=rabbitmq
    depends_on:
      - rabbitmq
    networks:
      - netwdocker

  detectlangworker:
    build: backend/detectlangworker/.
    # environment:
    #   - MQ_HOST=rabbitmq
    depends_on:
      - rabbitmq
    networks:
      - netwdocker

networks:
  netwdocker: {}
